#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""Script to set up new local development environments"""

from os import errno
from subprocess import call
from _utils import show_error

def build_docker_environment():
    """Build and launch the local environment using Docker and Docker Compose."""
    try:
        call(['docker-compose', 'up', '--build'])
    except OSError as err:
        if err.errno == errno.ENOENT:
            show_error('missing', 'docker-compose')
        else:
            show_error('fatal')
            raise


def main():
    """Main function."""
    build_docker_environment()

if __name__ == '__main__':
    main()
