#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""Launch a local development environment and watch for changes."""

from os import errno
from subprocess import call
from _utils import show_error

def start_docker_environment():
    """Build and launch the local environment using Docker and Docker Compose."""
    try:
        call(['docker-compose', 'up'])
    except OSError as err:
        if err.errno == errno.ENOENT:
            show_error('missing', 'docker-compose')
        else:
            show_error('fatal')
            raise


def main():
    """Main function."""
    start_docker_environment()

if __name__ == '__main__':
    main()

